apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: storage
resources:
  - ../common
  - secrets.yaml
  - ingress.yaml
  - service.yaml
  - sts.yaml
commonLabels:
  app: vaultwarden