apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: storage
resources:
  - ../common
  - ingress.yaml
  - service.yaml
  - sts.yaml
commonLabels:
  app: vaultwarden
configMapGenerator:
  - name: vaultwarden-env
    envs:
      - .env