apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden
    namespace: storage
type: Opaque
data:
    DOMAIN: ENC[AES256_GCM,data:aQJ/yDIDLhfcgaHrMGO2AxyDTV9oZvgqe4Jw0YX7QA==,iv:xLcojPQfiq+CmJoVGoMReelTDyM7zgjYqQwnE2x8Vfg=,tag:4mhgS4Pvh0/iui8APZ00rw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-09-16T08:49:09Z"
    mac: ENC[AES256_GCM,data:VxRaJ9RmSdicCnUnawaUNVV6kuHGQuoDM6u0OHKNeUlLqwuwXLQ5SXIx5AhKtorXw44IN5mjfb7ci8pCjUtfDSICBLrTy0ea7LQCpTm9mB0jFd5hDUQpchFCywRYiec69uRLHfPBiqRCqXjTFHikQuJVAKu2lcAdR7YBJiok1SU=,iv:7wuRrEhF0EqIJzQQtrygNdXgh1smwH5e49l4omLYojs=,tag:AVybuUqgZZO3OB2jRcp7Cw==,type:str]
    pgp:
        - created_at: "2023-09-16T08:49:09Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAyyGYy7YCFAQAQ//afsb1PupGnHh6l1vDzMxYZzx1Y/F5nIuovBvxRe+rQ6y
            0SHj5ycMdNfE3kIsQ+rrFDj+h0k2oP2bEOf2qsziACZ8EuSEFkunPaEzVyvHLnvZ
            Dp6k0r5VNFbxsMLVR7DCAaPA1y70e0gRF1o9sR1MsE088AF8QK5BBZ7L6H7LwAOf
            /szm59yEM06OHUzfirSwqRpWBqQHfmzI0gTLZVVwA0NmM8OjrQf81gLTNsF0/KKn
            3toxZLHz443fF7zKf1D1cdk1KHhSDIcTtlkwkBiGu2ZJR+jiI+hDAc6bobSDazji
            AX3ywvPVRdSOQrt+gQuIdHxZxDU12RpiMWxuOG44MbBjpqM1ftqkXA+QaMubG5cL
            u+aOQuvmHvSqakOgwCglLfx1hnGAP+xaGD4qXCepQm5f7tzbxONi513oYZDLhGkU
            IR2VEX3dU2JtyNXK6P2TmFy6T4C6GLNp03GLsIacXoJT0+vpFhUH7jaCYq5H2da3
            wXqhBK4CEHmfg30mLyFSkHvJ3eLhkkdWwz5C1vPfiTiQNZXy/NjFg0oVECl2LVuj
            JaqCNmnw5J+d2wn3wRV7FWsoBSdp8jaKHXb+8pFcxSh1idSEx+TgiNpmoNM9PmLZ
            1LRm/HTrQ44T2kQ1Tqf0qFy1YlQZhxKx42NCZtbEVqIO7AywWJlx+NTVeJKutc3U
            ZgEJAhAQ+BhOCyV+bprdX6Am5thsN49wZC+q2FYUBb9/J1lfHNvuGNoSBLp+98UO
            eYQRM2+i77YvGHip34vNRNTogppoCZNWyATfS21jUaHs0eeq/2XGkL3+lkTRf2da
            yW6ljOdt7Q==
            =Kd0G
            -----END PGP MESSAGE-----
          fp: 75C3F62D6A9AA2165875F5C680A364E41D3C47AF
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
