apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: storage
resources:
  - ../common
  - nextcloud-secrets.yaml
  - nextcloud-headers-middleware.yaml
  - nextcloud-dav-middleware.yaml
  - ingress.yaml
  - sts.yaml
  - service.yaml
