apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: storage
resources:
  - namespace.yaml
  - nextcloud-secrets.yaml
  - middleware.yaml
  - ingress.yaml
  - sts.yaml
  - service.yaml
