apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: nextcloud-dav
  namespace: storage
spec:
  redirectRegex:
    regex: https://(.*)/.well-known/(card|cal)dav
    replacement: https://$$1/remote.php/dav/
    permanent: true