apiVersion: v1
data:
    NEXTCLOUD_ADMIN_PASSWORD: ENC[AES256_GCM,data:m5k8W/XpM4xGe+vESJAp/3sOfFNVj/D0yvC0sGI30rRqVwRb,iv:kC9QQZtnW34ad/BP1TdjfXQYUBS77n/JHdDCupJYzlM=,tag:V2dhsXk/gSIrj7EfV/FgkQ==,type:str]
    NEXTCLOUD_ADMIN_USER: ENC[AES256_GCM,data:uIdFoOvsr1fREsox,iv:1zkf/FBkpvt87XmthgdbJp50Jb/8u8k5X3R/M/nrDuM=,tag:4k/67zDt1yqu6aU9uwvVHg==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:ZUMyIKoE1UuIXINb,iv:hBG/t/5xap2blC1kPtSc6MeLC0V9QpYonOeUUWJxB0c=,tag:jnKmdFQnKpT5gFD1Gkv2gA==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:LLpZBDwI01Van5DGs+iFUyFEDfJ8Uqr7ZY3E+g==,iv:oSfBOpbpoEXSQuzJ4CZ3vpad6lxtxhxuXmkITKFHI3k=,tag:GImD0COsTX8GzAXxuxmLDQ==,type:str]
    REDIS_HOST_PASSWORD: ENC[AES256_GCM,data:tztukootdfhHVwMKcRxDMNArc7XQ5RyIBdAZJQ==,iv:/ZBJPd0C0BBNM1bB8GBBfV1aB/5tdOMzkJI8nW0TZI4=,tag:gc5xXfpOUUQG1YsITKq9xg==,type:str]
    SMTP_NAME: ENC[AES256_GCM,data:WF5hW6oOMMJzaZ2Ab7WD2rO0ISjyCFlAziIriA==,iv:6kNTVq8z9Meh/FHWcR7GkZIupCYW666e0ez7YphgwzE=,tag:jsJzXg+LBximeEz0RYS+nA==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:88K40sjVZrR7wY0l+JALjo1eY8ukJdj+,iv:H0Z+NapSc7V1F59auYriMlWm5i6UDS8eLEX/eulZO2g=,tag:0eFEZYfvN8Rfzy1YkxcVgA==,type:str]
    REDIS_HOST: ENC[AES256_GCM,data:PA7fTQRCdhTMmWbhBn2NwxWzYHJql8sq2S6R9L5blNyCJr6hp2PnGODx6a3Dvnhz,iv:JRtNCLrMFBz1drC7YCV5bVog5nO3P1o7AtOuHFyQwYw=,tag:iPN4kOBilqr4QP0yrAbksw==,type:str]
    REDIS_HOST_PORT: ENC[AES256_GCM,data:yfH691KN4sk=,iv:tncglHfiu/5aLMas4/69b/S8j9nLEzPUFk7O3t0ZMc0=,tag:D4Tg/APBD4TTjfhhmhht/w==,type:str]
    POSTGRES_HOST: ENC[AES256_GCM,data:6GdmgMY/Ghu204/MbNPX5HF+MGTNtXYU6hZX9KQbKcxLZqFZqRJ5NVJn+RjiFs5dr6+LuoXH3VU=,iv:DDzDKElN+gWZRdbVMHAT2O3azFQ7G2VFIf/pLCBRqQI=,tag:het8S3EYcO9q2thbcDSY7Q==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:W7sCUmovGXAOJMuS,iv:QdXMgUutlEQudc/5zqhi3NGHYOUtgu0EIwjXvpuTfY8=,tag:KU9czvoieRLEr+hgS40KHw==,type:str]
    NEXTCLOUD_TRUSTED_DOMAINS: ENC[AES256_GCM,data:frmC+8j26trQyJBfxTzU0KyJ0pWIyvGmAeGiJIBhmSYRiFqK8UYN+U8JFLbG+lpZqPcBlg==,iv:eW761iuY7HWjjsicWFbjKBdGv9VeSowVJBfS0Jwxx5Y=,tag:QoVyn4p5iqFv5K6DDXn2Gg==,type:str]
    OVERWRITEHOST: ENC[AES256_GCM,data:9LtKlQc09pk8ArjDrbZ2kQk+50ckOxu8Wxuvmw==,iv:HUY5A2Zre6W26ZKErjrv7kwNSoI/LrXb7RWzufkqImA=,tag:61hXRFDV9VUvUQe19FZBeg==,type:str]
    OVERWRITEPROTOCOL: ENC[AES256_GCM,data:auWQ+kKC8GU=,iv:Du/xxUr36QNt9OeasGAc1BwtCfdqr8TyqrHSuUc4nb4=,tag:3h+rUI1EbR+FPZkW8TA9vA==,type:str]
    OVERWRITECLIURL: ENC[AES256_GCM,data:RXj/Q+qLw6s+qz8liWZ9HxCHTa9iknehRAs+42nIEHaTd35pz37k6g==,iv:7R+GJ++ehKVWgEOsdddCXOfRU4+SHiUK1GkKMSxWPC0=,tag:+8pMC5c5SAkF0YHHcwr9oA==,type:str]
    TRUSTED_PROXIES: ENC[AES256_GCM,data:2jvaDPyQeJzBzQTmj7lgRdmjOXCDcusPzvJXOo0i0JXvLMLcT3OS0h82WoNb8j22,iv:YtWJrEL2GnL6LyfEpz9N3oN8hu1fsmbLjtHMw2HCnng=,tag:GsbBnFtS/YqKTUM2E7Q3Qw==,type:str]
    SMTP_HOST: ENC[AES256_GCM,data:jnnC3iQqEXA0Qj9lICbJpfWH60g=,iv:FVufVCxJqsPPji1kxanM7+k/jLeMKFgOX8AOtmPx5N4=,tag:ZKgznSo0bvVkiv7KVYXnlw==,type:str]
    SMTP_PORT: ENC[AES256_GCM,data:1Yispa/x2fA=,iv:VUgtpDV6GbhRVJSXNlkzlpca7UWap5tsWM81LSb41kE=,tag:PwlKafEcVs272GVXrOsvsA==,type:str]
    MAIL_FROM_ADDRESS: ENC[AES256_GCM,data:uqi55WZQj/JYyA/rG+59y10mwyuP6AGsBAYrtQ==,iv:XNqhXfQ4FMFFtW7oPRv1TmNq5eIz4xAWqp9ayjPTTH8=,tag:JMzU8O0X6Oaovbzery3sFA==,type:str]
kind: Secret
metadata:
    name: nextcloud
    namespace: storage
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-09-08T21:41:43Z"
    mac: ENC[AES256_GCM,data:tcZ3Nvz5/stUGopEyWEXa1vcMwdrPyQG+GzohwzxJI4HN9jZYHs7fp/raJ6HcZa6LDiE6AEbG4+4fDYEYrAawwl0xCG/kswizETb1vsNnhQu5gC1BI9ARfnNUn4eUYzb9KoY3/qlPIIGttjPYpyv4WoNpDSqXQtctgOk/8c1MQI=,iv:xXHqfXIDRxmsH0arzzhpvFvU8nXc92F7KVdcm3l7uRM=,tag:tKmEoOIlsZmLYki7ESXRQg==,type:str]
    pgp:
        - created_at: "2023-09-08T21:41:42Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAyyGYy7YCFAQARAAy9/SQIR7u+eevxCQQgqJJfD31KK6jPzs3OpKgq/gUS1C
            +kJ1qXf9MKlhmFY90TkVhixiIxC+BB5iZK03Z0J/LSL3IYUkhRD1bgIUsXVfUFVe
            mIWUiuNBLy4BuJrXP2ReQEqWq0qzyg8BFtz+1SF1weE9I1TiMErniqdz5KPpVrPt
            tKfbriZ8UW/lzitftQZphPe6dCTzDKqAkfzMMiO4/4xwMGV44vzjVVbuklbdAuSj
            brZZvkp0W6Bs51AHZMYQNbv3syPwLyxhzdFI53EMney+DMnVCE/qHtGJpta0oyYT
            LDt097fDMhw++evrncZWqB0UOw0O5Vx9mHT4qvc5SSaAMvDLDNXsw8OOp/fXud7F
            auUUOvJKS74r6HJAlIJ1IPV0+Md+soOEEvu8UmkNXg1Tiuk4DANcf5X+sPU4cM+S
            ouHqWuevuvj0C7daPJEqRaoUy2tYVBNvUFcd6tMad5SZI79d8g1KLFryAmkwJECH
            Wuwa7+7xEPXrQjenXSFCfpuTKY8wkLbYw6OT26zAKeaYOAs7jAc5up6lksIqXKPJ
            nrDKHLgCJBHUZEnZ5E6eC228nypMOzLilNt7vftoeH6p/v9Ji92eIXaXvZSotRXX
            tZVcehT2J/V7c7pUDkZ+BuBMsFLAbRTWZ5RWTYSH0U/sC3C71haPhVeA22Ye3pPU
            aAEJAhBiwr8FgKoBHERM7BxOYvhl0gsPeYO9aDuY0poPXuV9NattKk7gwqQ8kLA/
            fZ/uoXAOk74PSRzcGH8ld0b3U4TG130cDRLRtE0or3yJtICGzAgXamakWtPI5ne5
            tUscvSgolKGq
            =4xnN
            -----END PGP MESSAGE-----
          fp: 75C3F62D6A9AA2165875F5C680A364E41D3C47AF
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
